<script>
  import { onMount } from 'svelte';
  import { categories } from '$lib/data/store.js';

  // ── Auth ──────────────────────────────────────────────────────
  const ADMIN_USER = 'admin';
  const ADMIN_PASS = 'bizdir2025';

  let authed = false;
  let loginUser = '';
  let loginPass = '';
  let loginErr  = '';

  function doLogin() {
    if (loginUser === ADMIN_USER && loginPass === ADMIN_PASS) {
      authed = true;
      loginErr = '';
      if (typeof localStorage !== 'undefined')
        localStorage.setItem('bizdir_admin', '1');
    } else {
      loginErr = 'اسم المستخدم أو كلمة المرور غير صحيحة';
    }
  }
  function doLogout() {
    authed = false;
    if (typeof localStorage !== 'undefined')
      localStorage.removeItem('bizdir_admin');
  }

  // ── State ─────────────────────────────────────────────────────
  let tab = 'dashboard'; // dashboard | listings | add | settings
  let listings = [];
  let toast = '';
  let toastType = 'success';

  function showToast(msg, type = 'success') {
    toast = msg; toastType = type;
    setTimeout(() => toast = '', 3200);
  }

  // ── Persist ───────────────────────────────────────────────────
  function save() {
    if (typeof localStorage !== 'undefined')
      localStorage.setItem('bizdir_listings', JSON.stringify(listings));
  }
  function load() {
    if (typeof localStorage === 'undefined') return;
    const s = localStorage.getItem('bizdir_listings');
    if (s) listings = JSON.parse(s);
    if (localStorage.getItem('bizdir_admin')) authed = true;
  }

  onMount(load);

  // ── Blank form ────────────────────────────────────────────────
  function blank() {
    return {
      id: 'lst-' + Date.now(),
      slug: '',
      name: '', nameEn: '',
      category: '',
      subcategory: '',
      description: '', descriptionEn: '',
      rating: 4.5, reviewCount: 0,
      priceRange: '$$',
      priceMin: 0, priceMax: 0,
      city: '', cityEn: '',
      address: '',
      phone: '', email: '', website: '',
      verified: true, featured: false,
      tags: '',
      services: '',
      openHours: '',
      image: '',
      established: new Date().getFullYear(),
    };
  }

  let form = blank();
  let editId = null;
  let deleteConfirm = null;
  let searchQ = '';
  let filterCat = '';

  // ── Slug auto-gen ─────────────────────────────────────────────
  function toSlug(s) {
    return s.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '').substring(0, 60);
  }
  $: if (form.nameEn && !editId) form.slug = toSlug(form.nameEn);

  // ── CRUD ──────────────────────────────────────────────────────
  function submitForm() {
    if (!form.name || !form.category || !form.slug) {
      showToast('يرجى ملء الحقول المطلوبة: الاسم، التصنيف، المعرّف', 'error'); return;
    }
    const entry = {
      ...form,
      tags: form.tags.split(',').map(t => t.trim()).filter(Boolean),
      services: form.services.split(',').map(s => s.trim()).filter(Boolean),
      rating: parseFloat(form.rating) || 4.5,
      reviewCount: parseInt(form.reviewCount) || 0,
      priceMin: parseInt(form.priceMin) || 0,
      priceMax: parseInt(form.priceMax) || 0,
      established: parseInt(form.established) || 2020,
    };
    if (editId) {
      listings = listings.map(l => l.id === editId ? entry : l);
      editId = null;
      showToast('تم تحديث السجل بنجاح ✅');
    } else {
      listings = [entry, ...listings];
      showToast('تمت إضافة السجل بنجاح ✅');
    }
    save();
    form = blank();
    tab = 'listings';
  }

  function startEdit(l) {
    editId = l.id;
    form = {
      ...l,
      tags: Array.isArray(l.tags) ? l.tags.join(', ') : l.tags,
      services: Array.isArray(l.services) ? l.services.join(', ') : l.services,
    };
    tab = 'add';
  }

  function confirmDelete(id) { deleteConfirm = id; }
  function doDelete() {
    listings = listings.filter(l => l.id !== deleteConfirm);
    deleteConfirm = null;
    save();
    showToast('تم حذف السجل', 'error');
  }

  function toggleFeatured(id) {
    listings = listings.map(l => l.id === id ? { ...l, featured: !l.featured } : l);
    save();
  }
  function toggleVerified(id) {
    listings = listings.map(l => l.id === id ? { ...l, verified: !l.verified } : l);
    save();
  }

  // ── Export store.js ───────────────────────────────────────────
  function exportStore() {
    const code = `// Auto-generated by BizDir Pro Admin — ${new Date().toLocaleString('ar')}
// Copy this file to: src/lib/data/store.js

export const siteConfig = {
  name: 'BizDir Pro',
  tagline: 'دليل الأعمال الأول في المنطقة',
  taglineEn: "The Region's Premier Business Directory",
  description: 'منصة B2B متكاملة تجمع أفضل الشركات والمحلات التجارية',
  contact: {
    email: 'info@bizdir.pro',
    phone: '+966 50 000 0000',
    address: 'الرياض، المملكة العربية السعودية',
    social: {
      twitter: 'https://twitter.com/bizdirpro',
      linkedin: 'https://linkedin.com/company/bizdirpro',
      instagram: 'https://instagram.com/bizdirpro',
    }
  }
};

export const categories = ${JSON.stringify(categories, null, 2)};

export const listings = ${JSON.stringify(listings.map(l => ({
      ...l,
      tags: Array.isArray(l.tags) ? l.tags : l.tags.split(',').map(t => t.trim()).filter(Boolean),
      services: Array.isArray(l.services) ? l.services : l.services.split(',').map(s => s.trim()).filter(Boolean),
    })), null, 2)};

export function getListingBySlug(slug) {
  return listings.find(l => l.slug === slug) ?? null;
}
export function getListingsByCategory(categoryId) {
  return listings.filter(l => l.category === categoryId);
}
export function getFeaturedListings(limit = 6) {
  return listings.filter(l => l.featured).slice(0, limit);
}
export function searchListings({ query = '', category = '', city = '', priceRange = '' } = {}) {
  const q = query.toLowerCase();
  return listings.filter(l => {
    const matchQuery = !q || l.name.toLowerCase().includes(q) || l.nameEn.toLowerCase().includes(q) || l.description.toLowerCase().includes(q) || l.tags.some(t => t.toLowerCase().includes(q));
    const matchCat   = !category   || l.category   === category;
    const matchCity  = !city       || l.cityEn     === city || l.city === city;
    const matchPrice = !priceRange || l.priceRange  === priceRange;
    return matchQuery && matchCat && matchCity && matchPrice;
  });
}
export const cities = [...new Set(listings.map(l => l.cityEn))];
export const priceRanges = ['$', '$$', '$$$', '$$$$'];
`;
    const blob = new Blob([code], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'store.js'; a.click();
    URL.revokeObjectURL(url);
    showToast('تم تصدير store.js — انسخه إلى src/lib/data/ ✅');
  }

  // ── Stats ─────────────────────────────────────────────────────
  $: stats = {
    total: listings.length,
    featured: listings.filter(l => l.featured).length,
    verified: listings.filter(l => l.verified).length,
    cats: [...new Set(listings.map(l => l.category))].length,
  };

  $: filtered = listings.filter(l => {
    const q = searchQ.toLowerCase();
    const mq = !q || l.name.toLowerCase().includes(q) || (l.nameEn||'').toLowerCase().includes(q);
    const mc = !filterCat || l.category === filterCat;
    return mq && mc;
  });

  const priceRanges = ['$', '$$', '$$$', '$$$$'];
</script>

<svelte:head>
  <title>لوحة التحكم — BizDir Pro Admin</title>
</svelte:head>

<!-- ── LOGIN ──────────────────────────────────────────────────── -->
{#if !authed}
<div class="min-h-screen bg-slate-950 flex items-center justify-center p-4">
  <div class="w-full max-w-sm">
    <!-- Logo -->
    <div class="text-center mb-8">
      <div class="w-14 h-14 rounded-2xl bg-gradient-to-br from-gold-500 to-gold-700 flex items-center justify-center mx-auto mb-4 shadow-xl shadow-gold-900/40">
        <span class="text-white font-display font-bold text-2xl">B</span>
      </div>
      <h1 class="font-arabic font-black text-2xl text-white">BizDir <span class="text-gold-400">Admin</span></h1>
      <p class="font-arabic text-slate-400 text-sm mt-1">لوحة تحكم المدير</p>
    </div>

    <div class="bg-white/5 border border-white/10 rounded-2xl p-6 backdrop-blur-sm">
      {#if loginErr}
        <div class="mb-4 px-4 py-2.5 bg-red-500/20 border border-red-500/30 text-red-300 font-arabic text-sm rounded-xl">{loginErr}</div>
      {/if}

      <div class="mb-4">
        <label class="block font-arabic text-sm text-slate-300 mb-1.5">اسم المستخدم</label>
        <input bind:value={loginUser} type="text" placeholder="admin"
          class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white font-arabic text-sm placeholder-slate-500 focus:outline-none focus:border-gold-500 transition"
          on:keydown={e => e.key === 'Enter' && doLogin()} />
      </div>
      <div class="mb-6">
        <label class="block font-arabic text-sm text-slate-300 mb-1.5">كلمة المرور</label>
        <input bind:value={loginPass} type="password" placeholder="••••••••"
          class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white font-arabic text-sm placeholder-slate-500 focus:outline-none focus:border-gold-500 transition"
          on:keydown={e => e.key === 'Enter' && doLogin()} />
      </div>
      <button on:click={doLogin}
        class="w-full py-3 bg-gold-600 hover:bg-gold-500 text-white font-arabic font-bold rounded-xl transition-all hover:scale-[1.02] shadow-lg shadow-gold-900/30">
        دخول إلى اللوحة
      </button>
      <p class="font-arabic text-slate-500 text-xs text-center mt-4">
        admin / bizdir2025
      </p>
    </div>
  </div>
</div>

<!-- ── DASHBOARD ───────────────────────────────────────────────── -->
{:else}
<div class="min-h-screen bg-slate-100 flex" dir="rtl">

  <!-- Sidebar -->
  <aside class="w-60 bg-slate-950 text-white flex flex-col shrink-0 fixed top-0 bottom-0 right-0 z-40">
    <!-- Brand -->
    <div class="px-5 py-5 border-b border-white/10">
      <div class="flex items-center gap-2.5">
        <div class="w-8 h-8 rounded-lg bg-gradient-to-br from-gold-500 to-gold-700 flex items-center justify-center">
          <span class="text-white font-display font-bold text-sm">B</span>
        </div>
        <div>
          <p class="font-arabic font-bold text-sm text-white leading-tight">BizDir <span class="text-gold-400">Admin</span></p>
          <p class="font-arabic text-slate-500 text-xs">لوحة التحكم</p>
        </div>
      </div>
    </div>

    <!-- Nav -->
    <nav class="flex-1 p-3 space-y-1 overflow-y-auto">
      {#each [
        { id: 'dashboard', icon: '📊', label: 'لوحة المعلومات' },
        { id: 'listings',  icon: '🏪', label: 'السجلات التجارية' },
        { id: 'add',       icon: '➕', label: editId ? 'تعديل سجل' : 'إضافة سجل' },
        { id: 'export',    icon: '💾', label: 'تصدير البيانات' },
      ] as item}
        <button
          on:click={() => { if (item.id === 'export') exportStore(); else { tab = item.id; if (item.id === 'add' && !editId) form = blank(); } }}
          class="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl font-arabic text-sm transition-all
            {tab === item.id ? 'bg-gold-600 text-white font-bold' : 'text-slate-400 hover:bg-white/10 hover:text-white'}"
        >
          <span class="text-base">{item.icon}</span>
          <span>{item.label}</span>
          {#if item.id === 'listings' && listings.length}
            <span class="mr-auto px-2 py-0.5 bg-gold-500/30 text-gold-300 text-xs rounded-full">{listings.length}</span>
          {/if}
        </button>
      {/each}
    </nav>

    <!-- Logout -->
    <div class="p-3 border-t border-white/10">
      <a href="/" class="flex items-center gap-2 px-3 py-2 text-slate-400 hover:text-white font-arabic text-sm rounded-xl hover:bg-white/10 transition mb-1">
        <span>🌐</span> عرض الموقع
      </a>
      <button on:click={doLogout} class="w-full flex items-center gap-2 px-3 py-2 text-slate-400 hover:text-red-400 font-arabic text-sm rounded-xl hover:bg-red-500/10 transition">
        <span>🚪</span> تسجيل الخروج
      </button>
    </div>
  </aside>

  <!-- Main content -->
  <div class="flex-1 mr-60 flex flex-col min-h-screen">

    <!-- Topbar -->
    <header class="bg-white border-b border-slate-200 px-6 py-3.5 flex items-center justify-between sticky top-0 z-30 shadow-sm">
      <h1 class="font-arabic font-bold text-slate-900 text-lg">
        {#if tab === 'dashboard'}لوحة المعلومات
        {:else if tab === 'listings'}إدارة السجلات
        {:else if tab === 'add'}{editId ? 'تعديل سجل' : 'إضافة سجل جديد'}
        {/if}
      </h1>
      <div class="flex items-center gap-3">
        <button on:click={exportStore} class="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white font-arabic text-xs font-bold rounded-lg transition">
          💾 تصدير store.js
        </button>
        <div class="w-8 h-8 rounded-full bg-gold-100 flex items-center justify-center text-sm font-bold text-gold-700">أ</div>
      </div>
    </header>

    <!-- Page body -->
    <main class="flex-1 p-6 overflow-auto">

      <!-- ── DASHBOARD TAB ── -->
      {#if tab === 'dashboard'}
        <!-- Stats cards -->
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          {#each [
            { label: 'إجمالي السجلات',  value: stats.total,    icon: '🏪', color: 'blue'    },
            { label: 'المميّزة',          value: stats.featured, icon: '⭐', color: 'amber'   },
            { label: 'الموثّقة',         value: stats.verified, icon: '✅', color: 'emerald' },
            { label: 'التصنيفات',        value: stats.cats,     icon: '📂', color: 'purple'  },
          ] as s}
            <div class="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
              <div class="flex items-center justify-between mb-3">
                <span class="text-2xl">{s.icon}</span>
                <span class="text-3xl font-display font-bold
                  {s.color === 'blue' ? 'text-blue-600' : s.color === 'amber' ? 'text-amber-500' : s.color === 'emerald' ? 'text-emerald-600' : 'text-purple-600'}">
                  {s.value}
                </span>
              </div>
              <p class="font-arabic text-sm text-slate-500">{s.label}</p>
            </div>
          {/each}
        </div>

        <!-- Recent listings table -->
        <div class="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden mb-6">
          <div class="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
            <h2 class="font-arabic font-bold text-slate-900">آخر السجلات المضافة</h2>
            <button on:click={() => { tab = 'add'; form = blank(); editId = null; }} class="text-xs font-arabic text-gold-600 hover:underline">+ إضافة جديد</button>
          </div>
          {#if listings.length === 0}
            <div class="p-12 text-center">
              <div class="text-5xl mb-3">📭</div>
              <p class="font-arabic text-slate-500">لا توجد سجلات بعد</p>
              <button on:click={() => { tab = 'add'; form = blank(); }} class="mt-4 px-4 py-2 bg-gold-600 text-white font-arabic text-sm font-bold rounded-xl hover:bg-gold-700 transition">أضف أول سجل</button>
            </div>
          {:else}
            <div class="overflow-x-auto">
              <table class="w-full text-sm font-arabic">
                <thead class="bg-slate-50 text-slate-500 text-xs">
                  <tr>
                    <th class="text-right px-5 py-3 font-medium">الاسم</th>
                    <th class="text-right px-5 py-3 font-medium">التصنيف</th>
                    <th class="text-right px-5 py-3 font-medium">المدينة</th>
                    <th class="text-right px-5 py-3 font-medium">التقييم</th>
                    <th class="text-right px-5 py-3 font-medium">الحالة</th>
                    <th class="text-right px-5 py-3 font-medium">إجراءات</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-slate-50">
                  {#each listings.slice(0, 8) as l (l.id)}
                    <tr class="hover:bg-slate-50/50 transition">
                      <td class="px-5 py-3">
                        <div class="flex items-center gap-3">
                          {#if l.image}
                            <img src={l.image} alt={l.name} class="w-8 h-8 rounded-lg object-cover shrink-0" />
                          {:else}
                            <div class="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center text-slate-400 text-xs">🏪</div>
                          {/if}
                          <div>
                            <p class="font-medium text-slate-900">{l.name}</p>
                            <p class="text-slate-400 text-xs">{l.slug}</p>
                          </div>
                        </div>
                      </td>
                      <td class="px-5 py-3 text-slate-600">{categories.find(c => c.id === l.category)?.name ?? l.category}</td>
                      <td class="px-5 py-3 text-slate-600">{l.city}</td>
                      <td class="px-5 py-3"><span class="text-gold-500 font-bold">★</span> {l.rating}</td>
                      <td class="px-5 py-3">
                        <div class="flex gap-1.5">
                          {#if l.verified}<span class="px-2 py-0.5 bg-emerald-50 text-emerald-700 text-xs rounded-full">موثّق</span>{/if}
                          {#if l.featured}<span class="px-2 py-0.5 bg-amber-50 text-amber-700 text-xs rounded-full">مميّز</span>{/if}
                        </div>
                      </td>
                      <td class="px-5 py-3">
                        <div class="flex gap-2">
                          <button on:click={() => startEdit(l)} class="text-blue-500 hover:text-blue-700 text-xs font-medium transition">تعديل</button>
                          <button on:click={() => confirmDelete(l.id)} class="text-red-400 hover:text-red-600 text-xs font-medium transition">حذف</button>
                        </div>
                      </td>
                    </tr>
                  {/each}
                </tbody>
              </table>
            </div>
          {/if}
        </div>

        <!-- Export CTA -->
        <div class="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl p-6 text-white">
          <div class="flex items-center justify-between flex-wrap gap-4">
            <div>
              <h3 class="font-arabic font-bold text-lg mb-1">جاهز لنشر التغييرات؟</h3>
              <p class="font-arabic text-slate-400 text-sm">صدِّر ملف store.js وانسخه إلى src/lib/data/ ثم أعِد البناء.</p>
            </div>
            <button on:click={exportStore} class="flex items-center gap-2 px-5 py-3 bg-gold-600 hover:bg-gold-500 text-white font-arabic font-bold rounded-xl shadow-lg transition-all hover:scale-105">
              💾 تصدير store.js الآن
            </button>
          </div>
        </div>

      <!-- ── LISTINGS TAB ── -->
      {:else if tab === 'listings'}
        <!-- Search + filter -->
        <div class="flex gap-3 mb-5 flex-wrap">
          <input bind:value={searchQ} type="text" placeholder="بحث بالاسم..."
            class="flex-1 min-w-[200px] px-4 py-2.5 bg-white border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
          <select bind:value={filterCat} class="px-4 py-2.5 bg-white border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition">
            <option value="">جميع التصنيفات</option>
            {#each categories as c}
              <option value={c.id}>{c.icon} {c.name}</option>
            {/each}
          </select>
          <button on:click={() => { tab = 'add'; form = blank(); editId = null; }}
            class="px-5 py-2.5 bg-gold-600 hover:bg-gold-700 text-white font-arabic font-bold text-sm rounded-xl transition">
            ➕ إضافة سجل
          </button>
        </div>

        {#if filtered.length === 0}
          <div class="bg-white rounded-2xl border border-slate-100 p-12 text-center">
            <div class="text-4xl mb-3">🔍</div>
            <p class="font-arabic text-slate-500">لا توجد نتائج</p>
          </div>
        {:else}
          <div class="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
            <div class="overflow-x-auto">
              <table class="w-full font-arabic text-sm">
                <thead class="bg-slate-50 text-slate-500 text-xs">
                  <tr>
                    <th class="text-right px-5 py-3 font-medium">السجل</th>
                    <th class="text-right px-5 py-3 font-medium hidden sm:table-cell">التصنيف</th>
                    <th class="text-right px-5 py-3 font-medium hidden md:table-cell">السعر</th>
                    <th class="text-right px-5 py-3 font-medium hidden lg:table-cell">التقييم</th>
                    <th class="text-right px-5 py-3 font-medium">مميّز</th>
                    <th class="text-right px-5 py-3 font-medium">موثّق</th>
                    <th class="text-right px-5 py-3 font-medium">إجراءات</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-slate-50">
                  {#each filtered as l (l.id)}
                    <tr class="hover:bg-slate-50/50 transition">
                      <td class="px-5 py-3">
                        <div class="flex items-center gap-3">
                          {#if l.image}
                            <img src={l.image} alt={l.name} class="w-9 h-9 rounded-xl object-cover shrink-0 border border-slate-100" />
                          {:else}
                            <div class="w-9 h-9 rounded-xl bg-slate-100 flex items-center justify-center text-lg shrink-0">🏪</div>
                          {/if}
                          <div>
                            <p class="font-medium text-slate-900 text-sm">{l.name}</p>
                            <p class="text-slate-400 text-xs">{l.city}</p>
                          </div>
                        </div>
                      </td>
                      <td class="px-5 py-3 text-slate-600 hidden sm:table-cell">
                        {categories.find(c => c.id === l.category)?.name ?? l.category}
                      </td>
                      <td class="px-5 py-3 hidden md:table-cell">
                        <span class="px-2 py-0.5 bg-slate-100 text-slate-700 text-xs rounded font-bold">{l.priceRange}</span>
                      </td>
                      <td class="px-5 py-3 hidden lg:table-cell">
                        <span class="text-gold-500">★</span> <strong class="text-slate-800">{l.rating}</strong>
                        <span class="text-slate-400 text-xs mr-1">({l.reviewCount})</span>
                      </td>
                      <td class="px-5 py-3">
                        <button on:click={() => toggleFeatured(l.id)} class="w-8 h-5 rounded-full transition-all relative {l.featured ? 'bg-amber-500' : 'bg-slate-200'}">
                          <span class="absolute top-0.5 w-4 h-4 bg-white rounded-full shadow transition-all {l.featured ? 'left-3.5' : 'left-0.5'}"></span>
                        </button>
                      </td>
                      <td class="px-5 py-3">
                        <button on:click={() => toggleVerified(l.id)} class="w-8 h-5 rounded-full transition-all relative {l.verified ? 'bg-emerald-500' : 'bg-slate-200'}">
                          <span class="absolute top-0.5 w-4 h-4 bg-white rounded-full shadow transition-all {l.verified ? 'left-3.5' : 'left-0.5'}"></span>
                        </button>
                      </td>
                      <td class="px-5 py-3">
                        <div class="flex gap-2 items-center">
                          <button on:click={() => startEdit(l)} class="px-2.5 py-1 bg-blue-50 text-blue-600 hover:bg-blue-100 text-xs font-medium rounded-lg transition">✏️ تعديل</button>
                          <button on:click={() => confirmDelete(l.id)} class="px-2.5 py-1 bg-red-50 text-red-500 hover:bg-red-100 text-xs font-medium rounded-lg transition">🗑 حذف</button>
                        </div>
                      </td>
                    </tr>
                  {/each}
                </tbody>
              </table>
            </div>
          </div>
        {/if}

      <!-- ── ADD / EDIT FORM TAB ── -->
      {:else if tab === 'add'}
        <div class="max-w-4xl mx-auto">
          <div class="bg-white rounded-2xl border border-slate-100 shadow-sm p-7">
            {#if editId}
              <div class="flex items-center justify-between mb-6 pb-5 border-b border-slate-100">
                <h2 class="font-arabic font-bold text-xl text-slate-900">✏️ تعديل سجل</h2>
                <button on:click={() => { editId = null; form = blank(); }} class="text-sm text-slate-400 hover:text-slate-600 font-arabic transition">إلغاء التعديل</button>
              </div>
            {:else}
              <h2 class="font-arabic font-bold text-xl text-slate-900 mb-6 pb-5 border-b border-slate-100">➕ إضافة سجل تجاري جديد</h2>
            {/if}

            <div class="space-y-6">
              <!-- Basic Info -->
              <section>
                <h3 class="font-arabic font-bold text-slate-700 text-sm mb-3 flex items-center gap-2">
                  <span class="w-6 h-6 bg-gold-100 text-gold-700 rounded-full flex items-center justify-center text-xs font-bold">1</span>
                  المعلومات الأساسية
                </h3>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">الاسم بالعربية *</label>
                    <input bind:value={form.name} type="text" placeholder="اسم العمل التجاري"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">الاسم بالإنجليزية</label>
                    <input bind:value={form.nameEn} type="text" placeholder="Business Name in English"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">المعرّف (Slug) *</label>
                    <input bind:value={form.slug} type="text" placeholder="business-name-slug"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition font-mono" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">التصنيف *</label>
                    <select bind:value={form.category}
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition bg-white">
                      <option value="">اختر التصنيف</option>
                      {#each categories as c}
                        <option value={c.id}>{c.icon} {c.name}</option>
                      {/each}
                    </select>
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">التصنيف الفرعي</label>
                    <input bind:value={form.subcategory} type="text" placeholder="مثال: Software Development"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">سنة التأسيس</label>
                    <input bind:value={form.established} type="number" min="1900" max="2025"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                </div>
              </section>

              <!-- Description -->
              <section>
                <h3 class="font-arabic font-bold text-slate-700 text-sm mb-3 flex items-center gap-2">
                  <span class="w-6 h-6 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center text-xs font-bold">2</span>
                  الوصف
                </h3>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">الوصف بالعربية</label>
                    <textarea bind:value={form.description} rows="3" placeholder="وصف موجز للعمل..."
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition resize-none"></textarea>
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">الوصف بالإنجليزية</label>
                    <textarea bind:value={form.descriptionEn} rows="3" placeholder="English description..."
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition resize-none"></textarea>
                  </div>
                </div>
              </section>

              <!-- Contact -->
              <section>
                <h3 class="font-arabic font-bold text-slate-700 text-sm mb-3 flex items-center gap-2">
                  <span class="w-6 h-6 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center text-xs font-bold">3</span>
                  معلومات الاتصال والموقع
                </h3>
                <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">المدينة (عربي)</label>
                    <input bind:value={form.city} type="text" placeholder="الرياض"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">City (English)</label>
                    <input bind:value={form.cityEn} type="text" placeholder="Riyadh"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">العنوان</label>
                    <input bind:value={form.address} type="text" placeholder="حي العليا، شارع..."
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">رقم الهاتف</label>
                    <input bind:value={form.phone} type="text" placeholder="+966 11 000 0000"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">البريد الإلكتروني</label>
                    <input bind:value={form.email} type="email" placeholder="info@business.com"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">الموقع الإلكتروني</label>
                    <input bind:value={form.website} type="url" placeholder="https://business.com"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                </div>
              </section>

              <!-- Pricing & Rating -->
              <section>
                <h3 class="font-arabic font-bold text-slate-700 text-sm mb-3 flex items-center gap-2">
                  <span class="w-6 h-6 bg-amber-100 text-amber-700 rounded-full flex items-center justify-center text-xs font-bold">4</span>
                  الأسعار والتقييم
                </h3>
                <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4">
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">نطاق السعر</label>
                    <select bind:value={form.priceRange}
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition bg-white">
                      {#each priceRanges as p}<option value={p}>{p}</option>{/each}
                    </select>
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">الحد الأدنى (ر.س)</label>
                    <input bind:value={form.priceMin} type="number" min="0"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">الحد الأقصى (ر.س)</label>
                    <input bind:value={form.priceMax} type="number" min="0"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">التقييم (1-5)</label>
                    <input bind:value={form.rating} type="number" min="1" max="5" step="0.1"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">عدد التقييمات</label>
                    <input bind:value={form.reviewCount} type="number" min="0"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                </div>
              </section>

              <!-- Tags, Services, Image -->
              <section>
                <h3 class="font-arabic font-bold text-slate-700 text-sm mb-3 flex items-center gap-2">
                  <span class="w-6 h-6 bg-purple-100 text-purple-700 rounded-full flex items-center justify-center text-xs font-bold">5</span>
                  الوسوم والخدمات والصورة
                </h3>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">الوسوم (مفصولة بفاصلة)</label>
                    <input bind:value={form.tags} type="text" placeholder="تقنية, برمجة, ذكاء اصطناعي"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">الخدمات (مفصولة بفاصلة)</label>
                    <input bind:value={form.services} type="text" placeholder="تطوير تطبيقات, استشارات, تصميم"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">رابط الصورة</label>
                    <input bind:value={form.image} type="url" placeholder="https://images.unsplash.com/..."
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                  <div>
                    <label class="block font-arabic text-xs font-medium text-slate-600 mb-1.5">ساعات العمل</label>
                    <input bind:value={form.openHours} type="text" placeholder="الأحد – الخميس: 9ص – 6م"
                      class="w-full px-3.5 py-2.5 border border-slate-200 rounded-xl font-arabic text-sm focus:outline-none focus:border-gold-400 transition" />
                  </div>
                </div>
              </section>

              <!-- Flags -->
              <section>
                <h3 class="font-arabic font-bold text-slate-700 text-sm mb-3 flex items-center gap-2">
                  <span class="w-6 h-6 bg-rose-100 text-rose-700 rounded-full flex items-center justify-center text-xs font-bold">6</span>
                  الحالة والظهور
                </h3>
                <div class="flex gap-6">
                  <label class="flex items-center gap-2.5 cursor-pointer">
                    <div class="relative">
                      <input type="checkbox" bind:checked={form.verified} class="sr-only" />
                      <div class="w-10 h-6 rounded-full transition-all {form.verified ? 'bg-emerald-500' : 'bg-slate-200'}">
                        <div class="absolute top-1 w-4 h-4 bg-white rounded-full shadow transition-all {form.verified ? 'left-5' : 'left-1'}"></div>
                      </div>
                    </div>
                    <span class="font-arabic text-sm text-slate-700">موثّق ✅</span>
                  </label>
                  <label class="flex items-center gap-2.5 cursor-pointer">
                    <div class="relative">
                      <input type="checkbox" bind:checked={form.featured} class="sr-only" />
                      <div class="w-10 h-6 rounded-full transition-all {form.featured ? 'bg-amber-500' : 'bg-slate-200'}">
                        <div class="absolute top-1 w-4 h-4 bg-white rounded-full shadow transition-all {form.featured ? 'left-5' : 'left-1'}"></div>
                      </div>
                    </div>
                    <span class="font-arabic text-sm text-slate-700">مميّز ⭐</span>
                  </label>
                </div>
              </section>

              <!-- Image preview -->
              {#if form.image}
                <div class="rounded-xl overflow-hidden h-40 border border-slate-200">
                  <img src={form.image} alt="معاينة" class="w-full h-full object-cover" />
                </div>
              {/if}

              <!-- Submit -->
              <div class="flex gap-3 pt-2">
                <button on:click={submitForm}
                  class="flex-1 py-3.5 bg-gold-600 hover:bg-gold-700 text-white font-arabic font-bold rounded-xl shadow-lg transition-all hover:scale-[1.02]">
                  {editId ? '💾 حفظ التعديلات' : '✅ إضافة السجل'}
                </button>
                <button on:click={() => { form = blank(); editId = null; tab = 'listings'; }}
                  class="px-5 py-3.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-arabic font-bold rounded-xl transition">
                  إلغاء
                </button>
              </div>
            </div>
          </div>
        </div>
      {/if}

    </main>
  </div>
</div>

<!-- ── DELETE CONFIRM MODAL ── -->
{#if deleteConfirm}
  <div class="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
    <div class="bg-white rounded-2xl shadow-2xl p-7 max-w-sm w-full">
      <div class="text-center mb-5">
        <div class="w-14 h-14 bg-red-50 rounded-2xl flex items-center justify-center text-2xl mx-auto mb-3">🗑️</div>
        <h3 class="font-arabic font-bold text-lg text-slate-900">تأكيد الحذف</h3>
        <p class="font-arabic text-slate-500 text-sm mt-1">هل أنت متأكد من حذف هذا السجل؟ لا يمكن التراجع.</p>
      </div>
      <div class="flex gap-3">
        <button on:click={doDelete} class="flex-1 py-2.5 bg-red-500 hover:bg-red-600 text-white font-arabic font-bold rounded-xl transition">نعم، احذف</button>
        <button on:click={() => deleteConfirm = null} class="flex-1 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-arabic font-bold rounded-xl transition">إلغاء</button>
      </div>
    </div>
  </div>
{/if}

<!-- ── TOAST ── -->
{#if toast}
  <div class="fixed bottom-6 left-6 z-50 px-5 py-3 rounded-xl shadow-xl font-arabic text-sm font-medium animate-fade-up flex items-center gap-2
    {toastType === 'success' ? 'bg-emerald-600 text-white' : 'bg-red-500 text-white'}">
    {toastType === 'success' ? '✅' : '❌'} {toast}
  </div>
{/if}
{/if}
